Repository house-mate-connect/house-connect, pull requests merged in 2024-05, with the labels that each got.

#10 Issue-9[여러 모달 선언 시 마지막 모달만 반영되는 문제]
  src/components/organisms/modals/AlertModal.tsx
  src/components/organisms/modals/ConfirmModal.tsx
  src/components/organisms/modals/ModalContainer.tsx
  src/components/organisms/modals/ProfileModal.tsx
  src/components/pages/ComponentTest.tsx
  src/components/templates/GlobalModal.tsx
  src/hooks/useModal.tsx
  src/stores/globalModal.store.ts
  src/types/modal.type.ts
Labels: bug, enhancement, status: resolved, urgent

#14 [Merge] HC-53(새로고침시 상태유지 기능) to HC-52-전역상태연결-검증로직구현
  src/components/pages/SignUpProfile.tsx
  src/components/templates/SignUpProfile1_1.template.tsx
  src/components/templates/SignUpProfile1_2.template.tsx
  src/components/templates/SignUpProfile1_3.template.tsx
  src/components/templates/SignUpProfile2_1.template.tsx
  src/components/templates/SignUpProfile2_2.template.tsx
  src/components/templates/SignUpProfile3_1.template.tsx
  src/components/templates/SignUpProfile3_2.template.tsx
  src/stores/sign.store.ts
Labels: enhancement, status: resolved

#16 Merge HC-46 To Dev
  src/App.tsx
  src/Router.tsx
  src/assets/icons/apple-logo.svg
  src/assets/icons/google-logo.svg
  src/assets/icons/kakaotalk-logo.svg
  src/assets/icons/meta-logo.svg
  src/components/pages/About.tsx
  src/components/pages/SignIn.tsx
  src/components/templates/Layout.template.tsx
  src/components/templates/SignInTemplate.tsx
  src/components/templates/SignLayout.template.tsx
  src/constants/iconSVG.tsx
  src/constants/toastMessage.ts
  src/hooks/useSignIn.ts
  src/index.css
  src/libs/fetch.ts
  src/libs/supabaseClient.ts
  src/libs/toast.ts
  src/stores/auth.store.ts
  src/types/auth.type.ts
  src/types/form.type.ts
  src/types/icon.type.ts
  src/types/supabase.ts
Labels: enhancement

#19 [Merge] Issue-13-Improve-layout-shift to dev
  src/components/molecules/TextField.tsx
  src/components/templates/SignUpIntroTemplate1.tsx
Labels: enhancement
