Repository house-mate-connect/house-connect, pull requests merged in 2024-06, with the labels that each got.

#22 Hc 52 전역상태연결 검증로직구현
  src/components/atoms/StepNavLink.tsx
  src/components/atoms/TextArea.tsx
  src/components/molecules/BadgeButtons.tsx
  src/components/molecules/FormItem.tsx
  src/components/molecules/StepNavLinks.tsx
  src/components/molecules/StepNavigation.tsx
  src/components/molecules/TextAreaField.tsx
  src/components/organisms/districtSelector/DistrictSelector.tsx
  src/components/organisms/modals/RoommateApplicationStatusModal.tsx
  src/components/organisms/modals/RoommateApplyModal.tsx
  src/components/pages/ComponentTest.tsx
  src/components/pages/SignUpProfile.tsx
  src/components/templates/GlobalModal.tsx
  src/components/templates/SignUpIntroTemplate1.tsx
  src/components/templates/SignUpProfile1_1.template.tsx
  src/components/templates/SignUpProfile1_2.template.tsx
  src/components/templates/SignUpProfile2_1.template.tsx
  src/components/templates/SignUpProfile2_2.template.tsx
  src/components/templates/SignUpProfile3_1.template.tsx
  src/components/templates/SignUpProfile3_2.template.tsx
  src/components/templates/SignUpProfileLayout.template.tsx
  src/constants/signUpProfileData.ts
  src/hooks/useModal.tsx
  src/stores/globalModal.store.ts
  src/stores/sign.store.ts
  src/types/icon.type.ts
  src/types/modal.type.ts
  src/types/signUp.type.ts
  tailwind.config.ts
Labels: status: resolved

#25 [Merge]: Issue-23-badgebutton-activeStyle to HC-70(House Register)
  src/components/atoms/Badge.tsx
  src/components/molecules/BadgeButton.tsx
  src/components/templates/HouseRegisterTemplate.tsx
Labels: status: resolved

#27 [Merge] Issue-26 to dev
  src/components/pages/SignUpProfile.tsx
  src/components/templates/SignUpProfileLayout.template.tsx
Labels: bug, status: resolved

#36 [Merge] HC-62-Zod-React-Hook-Form-Resolver to Dev
  package.json
  src/components/molecules/FormItem.tsx
  src/components/pages/SignUpProfile.tsx
  src/components/templates/SignInTemplate.tsx
  src/components/templates/SignUpIntroTemplate1.tsx
  src/components/templates/SignUpIntroTemplate2.tsx
  src/components/templates/SignUpProfile1_1.template.tsx
  src/components/templates/SignUpProfile1_2.template.tsx
  src/components/templates/SignUpProfile1_3.template.tsx
  src/components/templates/SignUpProfile2_1.template.tsx
  src/components/templates/SignUpProfile2_2.template.tsx
  src/components/templates/SignUpProfile3_1.template.tsx
  src/components/templates/SignUpProfile3_2.template.tsx
  src/components/templates/SignUpProfileLayout.template.tsx
  src/constants/signUpProfileData.ts
  src/hooks/useModal.tsx
  src/hooks/useSign.ts
  src/hooks/useSignUpProfile.ts
  src/stores/sign.store.ts
  src/types/auth.type.ts
  src/types/signUp.type.ts
  src/types/supabase.ts
  yarn.lock
Labels: enhancement

#39 [Merge] Issue-38-formitem-password to Dev
  src/components/molecules/FormItem.tsx
  src/components/templates/SignInTemplate.tsx
  src/components/templates/SignUpIntroTemplate2.tsx
Labels: enhancement, status: resolved

#42 [Merge] HC-108-SignUp-Split-Page To HC-107-OAuth-Name-Birth
  src/Router.tsx
  src/components/molecules/FormItem.tsx
  src/components/pages/SignUp.tsx
  src/components/pages/SignUpEmail.tsx
  src/components/pages/SignUpInfo.tsx
  src/components/templates/SignLayout.template.tsx
  src/components/templates/SignUpEmail.template.tsx
  src/components/templates/SignUpInfo.template.tsx
  src/hooks/useSign.ts
  src/stores/sign.store.ts
  src/types/auth.type.ts
Labels: enhancement

#40 [Merge] HC-98-User-Password-Reset to Dev
  src/Router.tsx
  src/components/pages/SignPasswordReset.tsx
  src/components/pages/SignUp.tsx
  src/components/pages/SignUpdatePassword.tsx
  src/components/templates/SignInTemplate.tsx
  src/components/templates/SignPasswordReset.template.tsx
  src/components/templates/SignUpdatePassword.template.tsx
  src/hooks/useSignPasswordReset.ts
  src/types/auth.type.ts
Labels: enhancement

#43 [Merge] HC-109-OAuth-Update-Logic to HC-107-OAuth-Name-Birth
  src/Router.tsx
  src/assets/icons/paper-clip.svg
  src/assets/icons/send.svg
  src/components/atoms/Img.tsx
  src/components/pages/About.tsx
  src/components/pages/Chat.tsx
  src/components/pages/Loading.tsx
  src/components/pages/SignIn.tsx
  src/components/pages/SignPasswordReset.tsx
  src/components/pages/SignUp.tsx
  src/components/pages/SignUpdatePassword.tsx
  src/components/templates/ChatList.tsx
  src/components/templates/ChatRoom.tsx
  src/components/templates/Layout.template.tsx
  src/components/templates/SignInTemplate.tsx
  src/components/templates/SignLayout.template.tsx
  src/components/templates/SignPasswordReset.template.tsx
  src/components/templates/SignUpdatePassword.template.tsx
  src/constants/iconSVG.tsx
  src/hooks/useSign.ts
  src/hooks/useSignPasswordReset.ts
  src/stores/auth.store.ts
  src/types/auth.type.ts
  src/types/icon.type.ts
  tailwind.config.ts
Labels: bug, enhancement

#46 [Merge] Issue-29 To Dev
  src/components/organisms/Carousel.tsx
  src/components/templates/SignUpProfileLayout.template.tsx
Labels: bug, status: resolved

#45 [Merge] Issue-28 To Dev
  src/components/molecules/DualInputRange.tsx
Labels: bug, status: resolved
